# Site settings
title: Dates & Nuts
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Dates & Nuts is a personal food journal
baseurl: "/dates-and-nuts" # the subpath of your site, e.g. /blog/
url: "http://keithnorm.github.io/" # the base hostname & protocol for your site
twitter_username: datesandnuts
github_username:  datesandnuts
instagram_username: datesandnuts
tagline: 'Confessions of a real food junkie'

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
gems:
- ./_plugins/tag_gen
- ./_plugins/top_posts_filter

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
